Repository AY2122S2-CS2103T-W12-1/tp, pull requests merged in 2022-03, with the labels that each got.

#67 Add standardised commit message
  .gitcommitmessage
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/festivecat.md
  docs/team/s7manth.md
  docs/team/zawedcvg.md
Labels: type.Miscellaneous

#72 [FEAT / CHG] Change Address into Mod
  build.gradle
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/index.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ContactList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyContactList.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Mod.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableContactList.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonContactListStorageTest/invalidAndValidPersonContactList.json
  src/test/data/JsonContactListStorageTest/invalidPersonContactList.json
  src/test/data/JsonSerializableContactListTest/duplicatePersonContactList.json
  src/test/data/JsonSerializableContactListTest/invalidPersonContactList.json
  src/test/data/JsonSerializableContactListTest/typicalPersonsContactList.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ContactListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/ModTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#75 [FEAT] Extend find functionality beyond just names
  .gitignore
  addressbook.log.0
  addressbook.log.0.lck
  config.json
  data/contactlist.json
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/festivecat.md
  preferences.json
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/CompoundedPredicates.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/ModContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TailorParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicates/CompoundedPredicatesTest.java
  src/test/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/ModContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/TagsContainsKeywordsPredicateTest.java
  tailorapp.log.0
Labels: type.Enhancement

#74 [FEAT] add 'group' parameter to a person
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug

#79 [FEAT] Navigate to previous commands
  src/main/java/seedu/address/history/InputHistory.java
  src/main/java/seedu/address/history/InputHistoryManager.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Enhancement, priority.High

#103 [CHG] update instances of AddressBook with Tailor or ContactList
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Documentation

#107 Branch update user guide to include mail functionality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MailAllCommand.java
Labels: type.Documentation

#111 Add Table of Contents, Fix SampleDataUtil
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug, type.Documentation

#94 [FEAT] Branch undo command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NewTaskCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTaskCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/TailorParser.java
  src/main/java/seedu/address/model/Content.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedContents.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ContentTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedContentsTest.java
  src/test/java/seedu/address/testutil/ContentBuilder.java
  src/test/java/seedu/address/testutil/TypicalContents.java
Labels: type.Enhancement

#110 Branch issue104 UGDG update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SetDefaultSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/SetDefaultSequenceDiagram.png
  docs/images/Ui.png
  docs/images/Ui_original.png
  docs/images/set_default_ex1.png
  docs/images/set_default_ex2.png
Labels: type.Documentation

#118 add help command's extension to user guide
  docs/UserGuide.md
Labels: type.Documentation

#125 [FEAT] Fix incorrect behaviour of refill prev command
  src/main/java/seedu/address/history/InputHistoryManager.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.High, severity.Medium

#128 Branch add mail testing
  build.gradle
  src/main/java/seedu/address/commons/util/MailUtil.java
  src/main/java/seedu/address/logic/commands/MailAllCommand.java
  src/main/java/seedu/address/logic/commands/MailIndexCommand.java
  src/main/java/seedu/address/logic/commands/MailXCommand.java
  src/main/java/seedu/address/logic/parser/MailIndexCommandParser.java
  src/main/java/seedu/address/logic/parser/MailXCommandParser.java
  src/test/java/seedu/address/commons/util/MailUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MailAllCommandTest.java
  src/test/java/seedu/address/logic/commands/MailIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/MailXCommandTest.java
  src/test/java/seedu/address/logic/commands/MailXDescriptorTest.java
  src/test/java/seedu/address/logic/parser/MailIndexCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MailXCommandParserTest.java
  src/test/java/seedu/address/testutil/MailXDescriptorBuilder.java
Labels: type.Enhancement, priority.High, type.Testing

#121 Update UG for newtask, find
  docs/UserGuide.md
  docs/images/findcommandUG/find-alex-bernice.png
  docs/images/findcommandUG/find-alex-charlotte.png
  docs/images/findcommandUG/initialstate.png
  docs/images/newTask-okay.png
  src/main/java/seedu/address/model/tasks/Description.java
  src/main/java/seedu/address/model/tasks/Task.java
  src/test/data/JsonSerializableTaskListTest/invalidTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/invalidTaskTaskList.json
  src/test/java/seedu/address/model/tasks/DescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: type.Documentation
