Repository AY2122S2-CS2103T-W12-1/tp, pull requests merged in 2022-04, with the labels that each got.

#130 [DOC] Add documentation for undo/redo in UG
  docs/UserGuide.md
  docs/images/undocommandUG/after_delete.png
  docs/images/undocommandUG/after_undo.png
  docs/images/undocommandUG/before_undo.png
  docs/images/undocommandUG/initial_state.png
Labels: type.Documentation

#131 [SPEC] add test cases to cater for import-csv command and csv util class
  src/main/java/seedu/address/logic/commands/ImportCsvCommand.java
  src/main/java/seedu/address/logic/parser/ImportCsvCommandParser.java
  src/test/data/ImportCsvTest/color_srgb.csv
  src/test/data/ImportCsvTest/sample-tutorial-data.csv
  src/test/java/seedu/address/commons/util/CsvUtilTest.java
  src/test/java/seedu/address/logic/commands/ImportCsvCommandTest.java
  src/test/java/seedu/address/logic/parser/ImportCsvCommandParserTest.java
Labels: priority.High, type.Testing

#133 Branch update ugdg mail help
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MailAllSequenceDiagram.puml
  docs/diagrams/MailIndexClassDiagram.puml
  docs/images/MailAllSequenceDiagram.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Documentation

#135 Branch dg update mail
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MailAllSequenceDiagram.puml
  docs/diagrams/MailIndexClassDiagram.puml
  docs/images/MailAllSequenceDiagram.png
  docs/images/helpMessage.png
Labels: type.Documentation

#137 [BUG] Fix application title
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#136 [BUG] Fix find command empty argument no error
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: type.Bug

#207 [BUG] Bugfix PE-dry run. See issues attached
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/tasks/Deadline.java
Labels: type.Bug

#211 Update DG with previous input feature
  docs/DeveloperGuide.md
  docs/diagrams/PreviousInputSequenceDiagram.puml
  docs/diagrams/PreviousInputState0.puml
  docs/diagrams/PreviousInputState1.puml
  docs/diagrams/PreviousInputState2.puml
  docs/diagrams/PreviousInputState3.puml
  docs/diagrams/PreviousInputState4.puml
  docs/diagrams/PreviousInputState5.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/PreviousInputSequenceDiagram.png
  docs/images/PreviousInputState0.png
  docs/images/PreviousInputState1.png
  docs/images/PreviousInputState2.png
  docs/images/PreviousInputState3.png
  docs/images/PreviousInputState4.png
  docs/images/PreviousInputState5.png
  src/main/java/seedu/address/history/InputHistory.java
  src/main/java/seedu/address/history/InputHistoryManager.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Documentation

#212 [BUG DOC] Fix UG bugs from PE, polish UG
  docs/UserGuide.md
  docs/images/UIexplanation/Base.png
  docs/images/UIexplanation/input-feedback-box.png
  docs/images/UIexplanation/invalid-add.png
  docs/images/UIexplanation/personcard.png
  docs/images/UIexplanation/studentlist.png
  docs/images/UIexplanation/taskcard.png
  docs/images/UIexplanation/tasklist.png
  docs/images/UIexplanation/valid-delete.png
  docs/images/Ui.png
  docs/team/festivecat.md
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, type.Documentation

#218 [FEAT] Add tests for prev input feature
  src/test/java/seedu/address/history/InputHistoryManagerTest.java
Labels: type.Testing

#229 Polish ug
  docs/UserGuide.md
Labels: type.Documentation

#227 Clear command support undo
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/VersionedContentsDiagram.puml
  docs/images/VersionedContentsClassDiagram.png
  docs/images/VersionedContentsDiagram.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultGroupCommand.java
  src/main/java/seedu/address/model/Content.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedContents.java
  src/main/java/seedu/address/model/person/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SetDefaultGroupCommandTest.java
  src/test/java/seedu/address/model/ContentTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedContentsTest.java
  src/test/java/seedu/address/testutil/ContentBuilder.java
Labels: type.Bug, priority.High

#228 Update dg model component
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Documentation, priority.High

#231 [DOC] Update UG docs
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#234 V1.4 DG undo and prev fixes
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#238 [DOC] Update module component
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Documentation, priority.High

#239 Increase Uiclassdiagram size, whitespace
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/team/festivecat.md
  src/main/java/seedu/address/commons/util/CsvUtil.java
Labels: type.Documentation
